// Front-Door Intent Routing v1 , approved evaluation corpus.
//
// Source of truth: docs/product/front-door-intent-routing-evaluation-v1.md
// Approved 1 August 2026 by the human project owner.
//
// Approved decision 15 makes this corpus a RELEASE GATE, not guidance.
// A failing scenario blocks release.
//
// Every scenario is fully synthetic. No real person, real message, real
// correspondence or private material is used. IDs are stable and match the
// approved document; do not renumber them.
//
// This file was generated from the approved markdown tables and then reviewed
// by hand. If the approved document changes, regenerate rather than edit.
//
// Person labels are held VERBATIM, matching the specification's rule that the
// user's own words are never normalised. The approved document's prose tidied
// them for readability ("mum", "father"); the executable contract keeps what the
// person actually typed ("MUM", "farther").

import type { FrontDoorIntentScenario } from "./types";

export const FRONT_DOOR_INTENT_CORPUS_VERSION = "front-door-intent-v1" as const;

export const frontDoorIntentCorpusV1: readonly FrontDoorIntentScenario[] = [
  {
    id: 'A01',
    text: 'my father needs care',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'father', relationship: 'father' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'A02',
    text: 'my sister needs help',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'sister', relationship: 'sister' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'A03',
    text: 'my mother needs looking after',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'mother', relationship: 'mother' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'A04',
    text: 'my brother needs help with a form',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_supporter', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'brother', relationship: 'brother' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'A05',
    text: 'my partner is struggling to manage at home',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'partner', relationship: 'partner' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'A06',
    text: 'my grandmother is not coping on her own',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'grandmother', relationship: 'grandmother' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'A07',
    text: 'my aunt has dementia and lives alone',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'aunt', relationship: 'aunt' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'A08',
    text: 'my uncle can\'t manage his bills any more',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need', 'possible_money_or_benefits_need', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'uncle', relationship: 'uncle' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'A09',
    text: 'my son has additional needs and I\'m exhausted',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_caring_role', 'possible_supporter', 'possible_functional_need', 'person_target_unclear'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'son', relationship: 'son' }],
      helpTarget: 'unknown',
      urgency: 'unclear_urgency',
    },
  },
  {
    id: 'A10',
    text: 'my daughter needs support at home',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'daughter', relationship: 'daughter' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'B01',
    text: 'I look after my neighbour',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_caring_role', 'possible_supporter', 'possible_person_needing_support', 'person_target_unclear'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'neighbour', relationship: 'neighbour' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'B02',
    text: 'I care for Dad full-time',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_caring_role', 'possible_supporter', 'possible_person_needing_support', 'person_target_unclear'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'Dad', relationship: 'Dad' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'B03',
    text: 'I\'m my wife\'s carer',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_caring_role', 'possible_supporter', 'possible_person_needing_support', 'person_target_unclear'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'wife', relationship: 'wife' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'B04',
    text: 'I\'ve been looking after my nan for three years',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_caring_role', 'possible_supporter', 'possible_person_needing_support', 'person_target_unclear'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'nan', relationship: 'nan' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'B05',
    text: 'I do everything for my husband now',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_caring_role', 'possible_supporter', 'possible_person_needing_support', 'possible_functional_need', 'person_target_unclear'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'husband', relationship: 'husband' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'B06',
    text: 'I wouldn\'t call myself a carer but I help my friend every day',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_caring_role', 'possible_supporter', 'possible_person_needing_support', 'person_target_unclear'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'friend', relationship: 'friend' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'B07',
    text: 'I cannot cope with caring for my wife',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_caring_role', 'possible_supporter', 'possible_person_needing_support', 'possible_urgent_need', 'person_target_unclear'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'wife', relationship: 'wife' }],
      helpTarget: 'unknown',
      urgency: 'unclear_urgency',
    },
  },
  {
    id: 'B08',
    text: 'I look after my mum and my dad',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_caring_role', 'possible_supporter', 'possible_person_needing_support', 'person_target_unclear'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'mum', relationship: 'mum' }, { personLabel: 'dad', relationship: 'dad' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'C01',
    text: 'my husband cannot wash himself',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'husband', relationship: 'husband' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'C02',
    text: 'Mum keeps falling',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need', 'possible_urgent_need', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'Mum', relationship: 'Mum' }],
      helpTarget: 'unknown',
      urgency: 'unclear_urgency',
    },
  },
  {
    id: 'C03',
    text: 'Dad can\'t manage the stairs any more',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'Dad', relationship: 'Dad' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'C04',
    text: 'mum is getting confused about her medication',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'mum', relationship: 'mum' }],
      helpTarget: 'unknown',
      urgency: 'unclear_urgency',
    },
  },
  {
    id: 'C05',
    text: 'my wife can\'t cook for herself now',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'wife', relationship: 'wife' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'C06',
    text: 'my father is incontinent and I don\'t know what to do',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need', 'possible_supporter', 'person_target_unclear'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'father', relationship: 'father' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'C07',
    text: 'my mother forgets whether she has eaten',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'mother', relationship: 'mother' }],
      helpTarget: 'unknown',
      urgency: 'unclear_urgency',
    },
  },
  {
    id: 'D01',
    text: 'Can Dad claim Attendance Allowance?',
    expected: {
      inputShape: 'direct_question',
      signals: ['possible_money_or_benefits_need', 'possible_person_needing_support'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'Dad', relationship: 'Dad' }],
      helpTarget: 'one_other_person',
      urgency: 'none_detected',
    },
  },
  {
    id: 'D02',
    text: 'My dad gets Attendance Allowance',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_money_or_benefits_need', 'possible_person_needing_support', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'dad', relationship: 'dad' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'D03',
    text: 'Mum gets PIP and I help with shopping',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_money_or_benefits_need', 'possible_person_needing_support', 'possible_caring_role', 'possible_supporter', 'person_target_unclear'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'Mum', relationship: 'Mum' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'D04',
    text: 'am I entitled to Carer\'s Allowance',
    expected: {
      inputShape: 'direct_question',
      signals: ['possible_money_or_benefits_need', 'possible_caring_role', 'possible_supporter'],
      mentionedUser: true,
      mentionedOtherPeople: [],
      helpTarget: 'self',
      urgency: 'none_detected',
    },
  },
  {
    id: 'D05',
    text: 'can I get anything for looking after my mum',
    expected: {
      inputShape: 'direct_question',
      signals: ['possible_money_or_benefits_need', 'possible_caring_role', 'possible_supporter', 'possible_person_needing_support'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'mum', relationship: 'mum' }],
      helpTarget: 'self',
      urgency: 'none_detected',
    },
  },
  {
    id: 'D06',
    text: 'does my nan qualify for pension credit',
    expected: {
      inputShape: 'direct_question',
      signals: ['possible_money_or_benefits_need', 'possible_person_needing_support'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'nan', relationship: 'nan' }],
      helpTarget: 'one_other_person',
      urgency: 'none_detected',
    },
  },
  {
    id: 'D07',
    text: 'should we be paying full council tax if mum has dementia',
    expected: {
      inputShape: 'direct_question',
      signals: ['possible_money_or_benefits_need', 'possible_person_needing_support', 'possible_functional_need', 'person_target_unclear'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'mum', relationship: 'mum' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'D08',
    text: 'what benefits can we claim',
    expected: {
      inputShape: 'direct_question',
      signals: ['possible_money_or_benefits_need', 'person_target_unclear'],
      mentionedUser: true,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'E01',
    text: 'my mum died last week',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_bereavement', 'possible_person_needing_support'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'mum', relationship: 'mum' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'E02',
    text: 'Dad died yesterday and I was his carer',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_bereavement', 'possible_caring_role', 'possible_supporter'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'Dad', relationship: 'Dad' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'E03',
    text: 'my husband passed away and I don\'t know what to sort out',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_bereavement', 'person_target_unclear'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'husband', relationship: 'husband' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'E04',
    text: 'I cared for my wife for eleven years and she\'s gone',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_bereavement', 'possible_caring_role', 'possible_supporter'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'wife', relationship: 'wife' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'E05',
    text: 'my Carer\'s Allowance stopped when mum died',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_bereavement', 'possible_money_or_benefits_need', 'possible_caring_role'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'mum', relationship: 'mum' }],
      helpTarget: 'self',
      urgency: 'none_detected',
    },
  },
  {
    id: 'E06',
    text: 'my grandad died and there are letters coming for him',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_bereavement', 'possible_person_needing_support'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'grandad', relationship: 'grandad' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'F01',
    text: 'mum has fallen and can\'t get up',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_urgent_need', 'possible_person_needing_support', 'possible_functional_need'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'mum', relationship: 'mum' }],
      helpTarget: 'one_other_person',
      urgency: 'possible_immediate_danger',
    },
  },
  {
    id: 'F02',
    text: 'dad has run out of his heart medication',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_urgent_need', 'possible_person_needing_support'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'dad', relationship: 'dad' }],
      helpTarget: 'one_other_person',
      urgency: 'possible_urgent_health_need',
    },
  },
  {
    id: 'F03',
    text: 'we have nowhere to stay tonight',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_urgent_need', 'possible_local_service_need'],
      mentionedUser: true,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'possible_urgent_practical_support',
    },
  },
  {
    id: 'F04',
    text: 'there is no food in the house and the heating is off',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_urgent_need', 'possible_money_or_benefits_need', 'possible_local_service_need'],
      mentionedUser: false,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'possible_urgent_practical_support',
    },
  },
  {
    id: 'F05',
    text: 'they are sending mum home tonight and there is no bed downstairs',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_urgent_need', 'possible_hospital_discharge', 'possible_person_needing_support', 'possible_functional_need'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'mum', relationship: 'mum' }],
      helpTarget: 'one_other_person',
      urgency: 'possible_urgent_practical_support',
    },
  },
  {
    id: 'F06',
    text: 'I think my brother is going to hurt himself',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_urgent_need', 'possible_person_needing_support'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'brother', relationship: 'brother' }],
      helpTarget: 'one_other_person',
      urgency: 'possible_immediate_danger',
    },
  },
  {
    id: 'F07',
    text: 'my neighbour is being threatened by someone for money',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_urgent_need', 'possible_person_needing_support'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'neighbour', relationship: 'neighbour' }],
      helpTarget: 'one_other_person',
      urgency: 'possible_immediate_danger',
    },
  },
  {
    id: 'G01',
    text: 'I need help urgently with this form',
    expected: {
      inputShape: 'direct_question',
      signals: [],
      mentionedUser: true,
      mentionedOtherPeople: [],
      helpTarget: 'self',
      urgency: 'none_detected',
    },
  },
  {
    id: 'G02',
    text: 'URGENT: your account requires attention',
    expected: {
      inputShape: 'document_or_message',
      signals: [],
      mentionedUser: false,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'G03',
    text: 'can someone get back to me as soon as possible',
    expected: {
      inputShape: 'direct_question',
      signals: [],
      mentionedUser: true,
      mentionedOtherPeople: [],
      helpTarget: 'self',
      urgency: 'none_detected',
    },
  },
  {
    id: 'G04',
    text: 'mum fell last year but she\'s fine now',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'mum', relationship: 'mum' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'G05',
    text: 'dad is a bit unsteady on his feet',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'dad', relationship: 'dad' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'G06',
    text: 'this is an emergency tariff change on my energy bill',
    expected: {
      inputShape: 'document_or_message',
      signals: ['possible_money_or_benefits_need'],
      mentionedUser: true,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'H01',
    text: 'Dad is coming home from hospital tomorrow',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_hospital_discharge', 'possible_person_needing_support', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'Dad', relationship: 'Dad' }],
      helpTarget: 'unknown',
      urgency: 'unclear_urgency',
    },
  },
  {
    id: 'H02',
    text: 'mum is in hospital and they\'re talking about discharge',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_hospital_discharge', 'possible_person_needing_support', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'mum', relationship: 'mum' }],
      helpTarget: 'unknown',
      urgency: 'unclear_urgency',
    },
  },
  {
    id: 'H03',
    text: 'they want to discharge my wife but the house isn\'t ready',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_hospital_discharge', 'possible_person_needing_support', 'possible_functional_need', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'wife', relationship: 'wife' }],
      helpTarget: 'unknown',
      urgency: 'unclear_urgency',
    },
  },
  {
    id: 'H04',
    text: 'my father was discharged last month and is struggling',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_hospital_discharge', 'possible_person_needing_support', 'possible_functional_need', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'father', relationship: 'father' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'I01',
    text: 'help with mum',
    expected: {
      inputShape: 'ambiguous_request',
      signals: ['possible_person_needing_support', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'mum', relationship: 'mum' }],
      helpTarget: 'unknown',
      urgency: 'unclear_urgency',
    },
  },
  {
    id: 'I02',
    text: 'care',
    expected: {
      inputShape: 'ambiguous_request',
      signals: ['person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'unclear_urgency',
    },
  },
  {
    id: 'I03',
    text: 'I don\'t know what to do',
    expected: {
      inputShape: 'ambiguous_request',
      signals: ['person_target_unclear'],
      mentionedUser: true,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'unclear_urgency',
    },
  },
  {
    id: 'I04',
    text: 'help',
    expected: {
      inputShape: 'ambiguous_request',
      signals: ['person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'unclear_urgency',
    },
  },
  {
    id: 'I05',
    text: 'benefits',
    expected: {
      inputShape: 'ambiguous_request',
      signals: ['possible_money_or_benefits_need', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'unclear_urgency',
    },
  },
  {
    id: 'I06',
    text: 'mum',
    expected: {
      inputShape: 'ambiguous_request',
      signals: ['person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'mum', relationship: 'mum' }],
      helpTarget: 'unknown',
      urgency: 'unclear_urgency',
    },
  },
  {
    id: 'I07',
    text: 'hi',
    expected: {
      inputShape: 'ambiguous_request',
      signals: [],
      mentionedUser: false,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'unclear_urgency',
    },
  },
  {
    id: 'I08',
    text: 'what can you do?',
    expected: {
      inputShape: 'orientation_request',
      signals: [],
      mentionedUser: false,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'I09',
    text: 'is this app any good for care stuff',
    expected: {
      inputShape: 'orientation_request',
      signals: [],
      mentionedUser: false,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'J01',
    text: 'my farther needs cair',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'farther', relationship: 'farther' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'J02',
    text: 'mum keeps falling over i cant cope',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need', 'possible_urgent_need', 'possible_caring_role', 'possible_supporter', 'person_target_unclear'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'mum', relationship: 'mum' }],
      helpTarget: 'unknown',
      urgency: 'unclear_urgency',
    },
  },
  {
    id: 'J03',
    text: 'atendance allowence for my dad',
    expected: {
      inputShape: 'direct_question',
      signals: ['possible_money_or_benefits_need', 'possible_person_needing_support'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'dad', relationship: 'dad' }],
      helpTarget: 'one_other_person',
      urgency: 'none_detected',
    },
  },
  {
    id: 'J04',
    text: 'MUM AND DAD BOTH NEED HELP',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'MUM', relationship: 'MUM' }, { personLabel: 'DAD', relationship: 'DAD' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'J05',
    text: 'I care for my wife and my mother',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_caring_role', 'possible_supporter', 'possible_person_needing_support', 'person_target_unclear'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'wife', relationship: 'wife' }, { personLabel: 'mother', relationship: 'mother' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'J06',
    text: 'CARE NEEDS ASSESSMENT\n\nREF: CNA-4471\nDATE: 12 AUGUST 2026\n\nAn assessment has been arranged.',
    expected: {
      inputShape: 'document_or_message',
      signals: [],
      mentionedUser: false,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'J07',
    text: 'my mum needs help. Sent from my iPhone',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'mum', relationship: 'mum' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'K01',
    text: 'I don\'t need help but my mum does',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'mum', relationship: 'mum' }],
      helpTarget: 'one_other_person',
      urgency: 'none_detected',
    },
  },
  {
    id: 'K02',
    text: 'I\'m fine, it\'s for a friend',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'friend', relationship: 'friend' }],
      helpTarget: 'one_other_person',
      urgency: 'none_detected',
    },
  },
  {
    id: 'K03',
    text: 'it\'s not for me, well partly for me',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['person_target_unclear', 'possible_supporter'],
      mentionedUser: true,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'K04',
    text: 'dad is fine now but last week he fell and I panicked',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need', 'possible_supporter'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'dad', relationship: 'dad' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'K05',
    text: 'my mother is independent but cannot manage forms or money',
    expected: {
      inputShape: 'ongoing_situation',
      signals: ['possible_person_needing_support', 'possible_functional_need', 'possible_money_or_benefits_need', 'person_target_unclear'],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'mother', relationship: 'mother' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'K06',
    text: 'Your father\'s account has been closed. I look after him and I don\'t understand this.',
    expected: {
      inputShape: 'document_or_message',
      signals: ['possible_person_needing_support', 'possible_caring_role', 'possible_supporter'],
      mentionedUser: true,
      mentionedOtherPeople: [{ personLabel: 'father', relationship: 'father' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'L01',
    text: 'Your father\'s account has been closed',
    expected: {
      inputShape: 'document_or_message',
      signals: [],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'father', relationship: 'father' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'L02',
    text: 'Please send your mother\'s death certificate',
    expected: {
      inputShape: 'document_or_message',
      signals: [],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'mother', relationship: 'mother' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'L03',
    text: 'Your PIP appointment is on 14 August 2026',
    expected: {
      inputShape: 'document_or_message',
      signals: [],
      mentionedUser: false,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'L04',
    text: 'This is your final bill for £43.17, due on 28 August 2026. Reference FINAL-4317.',
    expected: {
      inputShape: 'document_or_message',
      signals: [],
      mentionedUser: false,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'L05',
    text: 'From 1 September 2026 your monthly service price will rise from £28 to £31.',
    expected: {
      inputShape: 'document_or_message',
      signals: [],
      mentionedUser: false,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'L06',
    text: 'One final Direct Debit of £29.50 will be collected on 3 September 2026.',
    expected: {
      inputShape: 'document_or_message',
      signals: [],
      mentionedUser: false,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'L07',
    text: 'We have received your carer\'s assessment request. A social worker will contact you within 10 working days.',
    expected: {
      inputShape: 'document_or_message',
      signals: [],
      mentionedUser: false,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'L08',
    text: 'Thank you for notifying us of the death. The account review has started. Reference BRV-001.',
    expected: {
      inputShape: 'document_or_message',
      signals: [],
      mentionedUser: false,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'M01',
    text: 'We will never ask you to share your verification code',
    expected: {
      inputShape: 'document_or_message',
      signals: [],
      mentionedUser: false,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'M02',
    text: 'Send us the six-digit verification code you just received so we can secure your account.',
    expected: {
      inputShape: 'document_or_message',
      signals: [],
      mentionedUser: false,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'M03',
    text: 'Verify your account using this link within two hours or access will be suspended.',
    expected: {
      inputShape: 'document_or_message',
      signals: [],
      mentionedUser: false,
      mentionedOtherPeople: [],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
  {
    id: 'M04',
    text: 'Your mum\'s care home invoice is overdue. Pay £480 today using this link or she will be removed.',
    expected: {
      inputShape: 'document_or_message',
      signals: [],
      mentionedUser: false,
      mentionedOtherPeople: [{ personLabel: 'mum', relationship: 'mum' }],
      helpTarget: 'unknown',
      urgency: 'none_detected',
    },
  },
];

export const FRONT_DOOR_INTENT_EXPECTED_SCENARIO_COUNT = 90 as const;

/** Document controls. These must behave exactly as they do at e40285b. */
export const FRONT_DOOR_INTENT_DOCUMENT_CONTROL_IDS = [
  "G02", "G06", "J06", "K06",
  "L01", "L02", "L03", "L04", "L05", "L06", "L07", "L08",
  "M01", "M02", "M03", "M04",
] as const;

/** Scenarios requiring human review before release (approved corpus, section 9). */
export const FRONT_DOOR_INTENT_HUMAN_REVIEW_IDS = [
  "A01", "D03", "E01", "F01", "F02", "J06", "K06", "L03", "M04",
] as const;
